{
    'name': 'Location Auto',
    'version': '17.0.1.0',
    'summary': 'Gestion des états des lieux et portail client pour la location automobile',
    'category': 'Inventory/Customization',
    'author': 'Othmane Baz',
    'depends': ['base', 'mail', 'portal', 'website', 'account', 'bus', 'payment', 'payment_stripe', 'account_payment'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        'data/mock_data.xml',
        'views/vehicle_views.xml',
        'views/reservation_views.xml',
        'views/contract_views.xml',
        'views/inspection_views.xml',
        'views/partner_views.xml',
        'views/client_document_views.xml',
        'views/assets.xml',
        'views/website_templates.xml',
        'views/website_pages.xml',
        'views/portal_templates.xml',
        'views/support_templates.xml',
        'views/login_templates.xml',
        'views/menu.xml',
        'views/support_views.xml',
        'views/website_management.xml',
        'views/payment_stripe_templates.xml',
        'report/inspection_report.xml',
        'report/report_layout_keydrive.xml',
        'report/contract_report.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'post_init_hook': '_set_keydrive_layout',
}
